services:
  django:
    expose:
      - 8000
    entrypoint: /code/entrypoint.prod.sh
    command: gunicorn core.wsgi
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY}
    volumes:
      - static:/code/static/
      - media:/code/media/
  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static:/usr/share/nginx/static/
      - media:/usr/share/nginx/media/
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      django:
        condition: service_healthy


volumes:
  static:
  media:
