version: '3'

services:
  postgres:
    image: postgres:14.6-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
  redis:
    image: redis:alpine
  django:
    image: harleyking/dj-ms-core:${IMAGE_TAG:-latest}
    build:
      context: .
    restart: always
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
    env_file:
      - .env

volumes:
  postgres_data:
