services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  django:
    ports:
      - "${DJANGO_WEB_PORT:-8000}:8000"
    volumes:
      - .:/code/
  celery:
    volumes:
      - .:/code/
  celery-beat:
    volumes:
      - .:/code/
