apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-ms-core
  namespace: dj-ms-core
  labels:
    app.kubernetes.io/name: dj-ms-core
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dj-ms-core
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dj-ms-core
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: harleyking/dj-ms-core:latest
          command: ["/home/django/entrypoint.prod.sh", "gunicorn", "core.wsgi"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: dj-ms-core-config
            - secretRef:
                name: dj-ms-core-secret
